### PR TITLE
fix(MWTELE-271): Insights UI display fails

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses https://issues.redhat.com/browse/MWTELE-271, which encompasses a couple of issues that are completed by the two commits in this PR.

First, it was noted that the date format for the runtimes card was not consistent with the rest of the UI, this has been addressed by using the same formatting function that is being used by the host inventory page. It now borrows the "exact" function from the frontend-components DateFormat helper, which takes a UTC timestring and formats it in a way the HCC wants to show it.

Second, there were a couple of edge cases where the header for an accordion dropdown could have no title. This was due to the incoming report having an empty string for the workload, but can also happen if the app.name is empty (or in the case of JvmInstance, details['app.name']). This is a detail for the frontend specifically, because apparently you could overwrite this data somewhere and we'll want to have it displayed as normal; the backend won't let you have workload be empty I believe.

The solution here is that if it is detected that the workload is an empty string, we'll substitute it with "Unknown workload" if the app.name is also empty, otherwise the title will be instance.appName.

Screenshots:

- If the workload is empty, but there is an app.name:
appname-empty

- If both the workload and app.name are empty:
both-empty

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Comment by aptmac** [comment]
> ## ❗ Outdated dependencies error
> * Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

Addressed in: https://github.com/RedHatInsights/insights-runtimes-frontend/pull/16

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Comment by aptmac** [comment]
Latest backend changes have removed "details" from jvm instance. Previously the accordion title for jvm instances was using the details['app.name'] string, because unlike eap instance there is no appname field.

It made sense to roll these changes into this PR which is already dealing with redacted appname and workload strings. I've updated the jvm instance title to just use the workload strings for their title.

**Review by kittylyst — APPROVED** [review]
LGTM.

**Pull request merged**
