### PR TITLE
chore(fec): replace existing webpack config with fec config

### PR DESCRIPTION
**Pull request by aptmac**
This PR replaces the existing webpack config with the newer `fec.config.js` that is being adopted by the insights frontends.

Funny enough, the starter-app originally had this, but I worked backwards to better match the existing frontends as it was easier comparatively to work with. And now we're back here.

I've kept the `mock` run script in-tact, so locally we could hit a prism and json-server API for the inventory and runtimes backends respectively. This is used as before, using `npm run start:mock`, and having `npm run mock-server` in the insights-inventory-frontend repo, and `npm run mock-instances` in this repo. When I tried bringing over the prism mock api from inventory to here for whatever reason it doesn't populate the same amount of mock data, so I'll try that again in a future commit.

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Comment by aptmac** [comment]
Rebase ontop of master branch.

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Comment by aptmac** [comment]
Just noticed that specifying a port number to run as a LOCAL_APP isn't working at the moment. Will need to look into that before this goes in.

Issue:
Running `npm run start -- --port=8004` and instead runtimes gets started on port `8002`.

**Comment by aptmac** [comment]
Rebased on-top of master to bring in the latest changes.

Also did a couple of other changes, that include:
- Removing the "details" section from the mock instances data
- Added a sub-project to mock insights-host-inventory. The current prism dependency in insights-inventory-frontend is causing errors when trying to use it with the customProxy, so I've downgraded to the last version that works.
- Not that we use it, but removed the "beta" run scripts from the package.json
- Updated the readme to better reflect how the app runs locally today

To test with mocked data, you can run:

```bash
npm install
npm run start:mock
```

In two other terminals, run:
```bash
npm run start mock-instances
```

```bash
cd mock/mock-host-inventory
npm install
npm run start mock-server
```

And then navigate to https://stage.foo.redhat.com:1337/insights/inventory, which should start populating with fake data. Sometimes there are hiccups when running with mocked data, so if you don't see the Runtimes card display then try refreshing a few times.

**Review by kittylyst — APPROVED** [review]
LGTM.

**Pull request merged**
